name: Welcome to Elysian work

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Greet the Elysian work contributor
        uses: actions/first-interaction@v1
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Welcome to **Elysian work**!
            Thank you for opening your first issue. Our team will review it soon.
            Stay tuned and feel free to contribute more!
      - name:  Dummy build step
        run: echo "Build step would go here"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: echo "Deploying application..."
